#!/usr/bin/env bash
# Install nginx web server and add a custom header to the default server response

sudo apt update -y > /dev/null 2>&1
sudo apt install -y nginx > /dev/null 2>&1
sudo sed -i 's/server_name _;/server_name _;\n    add_header X-Served-By $hostname;/' /etc/nginx/sites-available/default
service nginx restart > /dev/null 2>&1
